/* tslint:disable */
/* eslint-disable */
/**
 * intract
 * intract is an rss reader and generator for the modern web
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeedItem
 */
export interface FeedItem {
    /**
     * 
     * @type {any}
     * @memberof FeedItem
     */
    authorName?: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeedItem
     */
    description?: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeedItem
     */
    guid?: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeedItem
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeedItem
     */
    imageText?: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeedItem
     */
    imageUrl?: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeedItem
     */
    link?: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeedItem
     */
    mediaDescription?: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeedItem
     */
    title?: any | null;
}

/**
 * Check if a given object implements the FeedItem interface.
 */
export function instanceOfFeedItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function FeedItemFromJSON(json: any): FeedItem {
    return FeedItemFromJSONTyped(json, false);
}

export function FeedItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'authorName': !exists(json, 'author_name') ? undefined : json['author_name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'guid': !exists(json, 'guid') ? undefined : json['guid'],
        'id': json['id'],
        'imageText': !exists(json, 'image_text') ? undefined : json['image_text'],
        'imageUrl': !exists(json, 'image_url') ? undefined : json['image_url'],
        'link': !exists(json, 'link') ? undefined : json['link'],
        'mediaDescription': !exists(json, 'media_description') ? undefined : json['media_description'],
        'title': !exists(json, 'title') ? undefined : json['title'],
    };
}

export function FeedItemToJSON(value?: FeedItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'author_name': value.authorName,
        'description': value.description,
        'guid': value.guid,
        'id': value.id,
        'image_text': value.imageText,
        'image_url': value.imageUrl,
        'link': value.link,
        'media_description': value.mediaDescription,
        'title': value.title,
    };
}

