/* tslint:disable */
/* eslint-disable */
/**
 * intract
 * intract is an rss reader and generator for the modern web
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Feed } from './Feed';
import {
    FeedFromJSON,
    FeedFromJSONTyped,
    FeedToJSON,
} from './Feed';

/**
 * 
 * @export
 * @interface FeedData
 */
export interface FeedData {
    /**
     * 
     * @type {Feed}
     * @memberof FeedData
     */
    feed: Feed;
    /**
     * 
     * @type {any}
     * @memberof FeedData
     */
    items: any | null;
}

/**
 * Check if a given object implements the FeedData interface.
 */
export function instanceOfFeedData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "feed" in value;
    isInstance = isInstance && "items" in value;

    return isInstance;
}

export function FeedDataFromJSON(json: any): FeedData {
    return FeedDataFromJSONTyped(json, false);
}

export function FeedDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'feed': FeedFromJSON(json['feed']),
        'items': json['items'],
    };
}

export function FeedDataToJSON(value?: FeedData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'feed': FeedToJSON(value.feed),
        'items': value.items,
    };
}

