/* tslint:disable */
/* eslint-disable */
/**
 * intract
 * intract is an rss reader for the modern web
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServerInfo
 */
export interface ServerInfo {
    /**
     * lowest length a password can be
     * @type {any}
     * @memberof ServerInfo
     */
    minPasswordLength: any | null;
    /**
     * how long the username needs to be
     * @type {any}
     * @memberof ServerInfo
     */
    minUsernameLength: any | null;
    /**
     * name of the server, this can be anything
     * @type {any}
     * @memberof ServerInfo
     */
    name: any | null;
    /**
     * the url the server is running on, something like `https://example.com`
     * @type {any}
     * @memberof ServerInfo
     */
    url: any | null;
}

/**
 * Check if a given object implements the ServerInfo interface.
 */
export function instanceOfServerInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "minPasswordLength" in value;
    isInstance = isInstance && "minUsernameLength" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function ServerInfoFromJSON(json: any): ServerInfo {
    return ServerInfoFromJSONTyped(json, false);
}

export function ServerInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'minPasswordLength': json['min_password_length'],
        'minUsernameLength': json['min_username_length'],
        'name': json['name'],
        'url': json['url'],
    };
}

export function ServerInfoToJSON(value?: ServerInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'min_password_length': value.minPasswordLength,
        'min_username_length': value.minUsernameLength,
        'name': value.name,
        'url': value.url,
    };
}

