/* tslint:disable */
/* eslint-disable */
/**
 * intract
 * intract is an rss reader and generator for the modern web
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemTime
 */
export interface SystemTime {
    /**
     * 
     * @type {any}
     * @memberof SystemTime
     */
    nanosSinceEpoch: any | null;
    /**
     * 
     * @type {any}
     * @memberof SystemTime
     */
    secsSinceEpoch: any | null;
}

/**
 * Check if a given object implements the SystemTime interface.
 */
export function instanceOfSystemTime(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "nanosSinceEpoch" in value;
    isInstance = isInstance && "secsSinceEpoch" in value;

    return isInstance;
}

export function SystemTimeFromJSON(json: any): SystemTime {
    return SystemTimeFromJSONTyped(json, false);
}

export function SystemTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemTime {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nanosSinceEpoch': json['nanos_since_epoch'],
        'secsSinceEpoch': json['secs_since_epoch'],
    };
}

export function SystemTimeToJSON(value?: SystemTime | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nanos_since_epoch': value.nanosSinceEpoch,
        'secs_since_epoch': value.secsSinceEpoch,
    };
}

