/**
 * intract
 * intract is an rss reader for the modern web
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("AccountApi", () => {
  let instance: api.AccountApi
  beforeEach(function() {
    instance = new api.AccountApi(config)
  });

  test("login", () => {
    const body: api.LoginData = undefined
    return expect(instance.login(body, {})).resolves.toBe(null)
  })
  test("register", () => {
    const body: api.RegisterData = undefined
    return expect(instance.register(body, {})).resolves.toBe(null)
  })
  test("whoami", () => {
    return expect(instance.whoami({})).resolves.toBe(null)
  })
})

describe("DocsApi", () => {
  let instance: api.DocsApi
  beforeEach(function() {
    instance = new api.DocsApi(config)
  });

  test("docsRedocGet", () => {
    return expect(instance.docsRedocGet({})).resolves.toBe(null)
  })
})

describe("ServerApi", () => {
  let instance: api.ServerApi
  beforeEach(function() {
    instance = new api.ServerApi(config)
  });

  test("serverInfo", () => {
    return expect(instance.serverInfo({})).resolves.toBe(null)
  })
})

