/* tslint:disable */
/* eslint-disable */
/**
 * intract
 * intract is an rss reader and generator for the modern web
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FeedData,
  FeedsInput,
  FollowFeedInputData,
} from '../models';
import {
    FeedDataFromJSON,
    FeedDataToJSON,
    FeedsInputFromJSON,
    FeedsInputToJSON,
    FollowFeedInputDataFromJSON,
    FollowFeedInputDataToJSON,
} from '../models';

export interface FollowFeedRequest {
    followFeedInputData: FollowFeedInputData;
}

export interface ShowFeedRequest {
    feedsInput: FeedsInput;
}

/**
 * 
 */
export class FeedApi extends runtime.BaseAPI {

    /**
     * follow a new feed
     * follow a feed
     */
    async followFeedRaw(requestParameters: FollowFeedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FeedData>> {
        if (requestParameters.followFeedInputData === null || requestParameters.followFeedInputData === undefined) {
            throw new runtime.RequiredError('followFeedInputData','Required parameter requestParameters.followFeedInputData was null or undefined when calling followFeed.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/authorized/feed/follow`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FollowFeedInputDataToJSON(requestParameters.followFeedInputData),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FeedDataFromJSON(jsonValue));
    }

    /**
     * follow a new feed
     * follow a feed
     */
    async followFeed(requestParameters: FollowFeedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FeedData> {
        const response = await this.followFeedRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * show the feeds
     */
    async showFeedRaw(requestParameters: ShowFeedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters.feedsInput === null || requestParameters.feedsInput === undefined) {
            throw new runtime.RequiredError('feedsInput','Required parameter requestParameters.feedsInput was null or undefined when calling showFeed.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/authorized/feed/show`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: FeedsInputToJSON(requestParameters.feedsInput),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * show the feeds
     */
    async showFeed(requestParameters: ShowFeedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.showFeedRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
