/* tslint:disable */
/* eslint-disable */
/**
 * intract
 * intract is an rss reader for the modern web
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ServerInfo,
} from '../models';
import {
    ServerInfoFromJSON,
    ServerInfoToJSON,
} from '../models';

/**
 * 
 */
export class ServerApi extends runtime.BaseAPI {

    /**
     * this is for getting information about the server. instances will be configured differently and these are the configurable parameters that are important for clients.
     * server info
     */
    async serverInfoRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServerInfo>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/server/info`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServerInfoFromJSON(jsonValue));
    }

    /**
     * this is for getting information about the server. instances will be configured differently and these are the configurable parameters that are important for clients.
     * server info
     */
    async serverInfo(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServerInfo> {
        const response = await this.serverInfoRaw(initOverrides);
        return await response.value();
    }

}
