on: [push, pull_request]
name: clippy

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: update rust
        run: rustup update
      - name: install clippy
        run: rustup component add clippy
      - name: Run Clippy
        run: |
          cd backend
          cargo clippy --all-targets --all-features