on: [push, pull_request]
name: clippy

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build frontend
        run: bash build_frontend.sh
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "intract"
      - name: Run Clippy
        run: |
          cargo clippy --all-targets --all-features
