name: codecov

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_and_upload_to_codecov:
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: hunter2
          POSTGRES_DB: intract
          POSTGRES_USER: intract
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: build frontend
        run: bash build_frontend.sh
      - name: rust-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: "0.22.0"
          args: "-- --include-ignored"
      - name: upload to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
      - name: archive coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: cobertura.xml
