name: codecov

on:
  push:
    branches:
    - "main"
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  upload_to_codecov:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend

    steps:
    - uses: actions/checkout@v3
    - name: install stuff
      run: |
        sudo apt-get update
        sudo apt-get install --yes postgresql-client
    - run: sudo systemctl start postgresql.service
    - run: sudo su - postgres -c "createuser intract"
    - run: sudo su - postgres -c "createdb -O intract intract"
    - name: rust-tarpaulin
      uses: actions-rs/tarpaulin@v0.1
      with:
        version: '0.22.0'
        args: '-- --include-ignored'
    - name: upload to codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{secrets.CODECOV_TOKEN}}
    - name: archive coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: cobertura.xml