on: [push, pull_request]
name: test

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_PASSWORD: postgres

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: install stuff
      run: |
        sudo apt-get update
        sudo apt-get install --yes postgresql-client
    - run: sudo systemctl start postgresql.service
    - run: sudo su - postgres -c "createuser --createdb intract"
    - name: Run tests
      run: |
        cargo test -- --include-ignored
